import os
print('#'*67)
print('#{:^65}#'.format('Joy Sirr PIP INSTALLER'))
print('#{:^65}#'.format('POWERED BY TEAM AWE & JOY SIRR'))
print('#'*67)

os.system('pip install time')
os.system('pip install telebot')
os.system('pip install python-cfonts')
os.system('pip install Topython')
os.system('pip install user_agent')
os.system('pip install fake_useragent')
os.system('pip install pyfiglet')
os.system('pip install selenium')
os.system('pip install requests')
os.system('pip install sys')
os.system('pip install py_compile')
os.system('pip install youtube_dl')
os.system('pip install uuid')
os.system('pip install time')
os.system('pip install os')
os.system('pip install random')
os.system('pip install datetime')
os.system('pip install string')
os.system('pip install secrets')
os.system('pip install webbrowser')
os.system('pip install hashlib')
os.system('pip install colorama')
os.system('pip install n')
os.system('pip install mm')
os.system('pip install new')
os.system('pip install sleep')
os.system('pip install BeautifulSoup')
os.system('pip install new')
os.system('pip install pafy')
os.system('pip install bs4')
os.system('pip install sys')
os.system('pip install json')
os.system('pip install random')
os.system('pip install uuid')
os.system('pip install secrets')
os.system('pip install datetime')
os.system('pip install argparse')
os.system('pip install InstagramAPI')
os.system('pip install string')
os.system('pip install uuid4')
os.system('pip install generate_user_agent')
os.system('pip install threading')
os.system('pip install json')
os.system('pip install datetime')
os.system('pip install token_hex')
os.system('pip install Fore')
os.system('pip install uuid')
os.system('pip install re')
os.system('pip install b')
os.system('pip install pysocks')
os.system('pip install curl2pyreqs')
os.system('pip install rich')
os.system('pip install requests')
os.system('pip install pycryptodome')
os.system('pip install telegram')
os.system('pip install ms4')

os.system('cls' if os.name == 'nt' else 'clear')

print('#'*67)
print("#{:^65}#".format("PIP INSTALLED SUCCESSFULLY"))
print("#{:^65}#".format("BY TEAM AWE • JOY SIRR • "))
print('#'*67)

exit()